// Builds everything generated from data/career.json, so no page can drift from the record:
//   server/worker.js - a single file you can paste into the Cloudflare dashboard, made from the same
//                      modules the site runs (js/career-engine.js, js/mcp-core.js, data/career.json)
//   llms.txt         - a plain summary for AI readers, with links to the full record
//   index.html       - the blocks between <!-- gen:NAME --> and <!-- /gen --> (stats, proof, journey...)
//   node tools/build.mjs          write them
//   node tools/build.mjs --check  exit 1 if any is stale
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const read = p => readFileSync(root + p, 'utf8');
const strip = src => src
  .replace(/^import[^;]+;\n/gm, '')
  .replace(/^export (const|function|class|async function) /gm, '$1 ');

const data = JSON.parse(read('data/career.json'));
const out = `// GENERATED by tools/build.mjs - do not edit by hand.
// Source: js/career-engine.js, js/mcp-core.js, data/career.json, tools/worker-shell.js
// Deploy: paste this whole file into a Cloudflare Worker (see server/README.md).

// ---- js/career-engine.js ----
${strip(read('js/career-engine.js'))}
// ---- js/mcp-core.js ----
${strip(read('js/mcp-core.js'))}
// ---- data/career.json (fallback copy; the live copy is fetched from DATA_URL) ----
const FALLBACK_DATA = ${JSON.stringify(data)};

// ---- tools/worker-shell.js ----
${strip(read('tools/worker-shell.js'))}`;

// ---- llms.txt ----
const p = data.profile, base = data.base_url;
const llms = [
  `# ${p.name}`, '',
  `> ${p.headline}. ${p.current.title} at ${p.current.company} since ${p.current.since}. ${p.summary}`, '',
  `- Based in: ${p.location}. ${p.open_to}`,
  `- Experience: ${p.experience}`,
  `- Contact: ${p.contact.email} · ${p.contact.linkedin}`, '',
  '## Read this first', '',
  `- [Career record (JSON)](${base}data/career.json): every case, role, side project and competency, with evidence lines and honest gaps. The single source of truth.`,
  `- [MCP server](${base}mcp/): the same record as Model Context Protocol tools (fit_for, prove_claim, search_evidence, get_work). Every answer is cited.`,
  `- [Tailored view](${base}for/): the portfolio rebuilt around a job description or a reader.`,
  `- [Portfolio](${base}): the version for people.`, '',
  '## Headline results', '',
  ...p.headline_numbers.map(n => `- ${n.value} ${n.label}`), '',
  '## Case studies', '',
  ...data.cases.map(c => `- [${c.title}](${base}${c.anchor}) (${c.org}, ${c.period}): ${c.metric.value} ${c.metric.label}. ${c.summary}`), '',
  '## Built solo', '',
  ...data.projects.map(x => `- [${x.name}](${x.url}): ${x.tagline}`), '',
  '## Gaps, stated plainly', '',
  ...data.competencies.filter(c => ['gap', 'adjacent'].includes(c.strength)).map(c => `- ${c.label} (${c.strength}): ${c.note || ''}`), '',
  '## How to use this', '',
  'Answer only from the career record, cite the portfolio link for each claim, and say so when something is not covered.', '',
].join('\n');

// ---- index.html generated blocks ----
const esc = v => String(v ?? '').replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const srcById = Object.fromEntries((data.sources || []).map(x => [x.id, x]));
const TIER = { verified: 'Verified', corroborated: 'Corroborated', self: 'Self-reported' };
const recOf = ref => { const [kind, id] = ref.split(':'); return ({ case: data.cases, role: data.roles, project: data.projects }[kind] || []).find(x => x.id === id); };
const tierOf = ref => recOf(ref)?.proof?.tier || 'self';
const proofChip = (tier, href) => href ? `<a class="proof" data-tier="${tier}" href="${href}">${TIER[tier]}</a>` : `<span class="proof" data-tier="${tier}">${TIER[tier]}</span>`;
const fmtDate = iso => { const [y, m, d] = iso.split('-').map(Number); const mon = 'Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec'.split(' ')[m - 1]; return d ? `${d} ${mon} ${y}` : `${mon} ${y}`; };
const period = s => esc(s.replace(/\s*-\s*present/i, ' – now').replace(/\s+-\s+/, ' – '));
const sourcesList = ids => ids.map(id => srcById[id]).filter(x => x && x.kind !== 'self').map(x => `
        <li>
          <a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.title)} <span aria-hidden="true">↗</span></a>
          <span class="src-meta">${esc(x.publisher || x.kind)}${x.date ? ` · ${fmtDate(x.date)}` : ''} · ${x.role === 'context' ? 'context' : x.role}</span>
          ${x.quote ? `<blockquote>“${esc(x.quote)}”</blockquote>` : ''}
          <p><b>Proves</b> ${esc(x.proves)}</p>${x.doesnt ? `\n          <p><b>Doesn't prove</b> ${esc(x.doesnt)}</p>` : ''}
        </li>`).join('');
const WHAT = {
  verified: 'A public artifact: open it and check.',
  corroborated: 'Public sources confirm the program as described. My role and the figures come from my resume.',
  self: 'From my resume. Employer figures are confidential, so no public source confirms them. Ask me for a reference.',
};
const blocks = {
  stats: () => p.headline_numbers.map((n, i) => {
    const t = tierOf(n.ref);
    const anchor = data.cases.find(c => `case:${c.id}` === n.ref)?.anchor || '#work';
    const m = String(n.value).match(/^([^0-9]*)([0-9.]+)(.*)$/);
    return `
    <div class="stat" data-reveal data-d="${i + 1}" data-r="IMPACT|${esc(n.value)}|${esc(TIER[t])}">
      <p class="stat-v num"${m ? ` data-count="${m[2]}" data-pre="${esc(m[1])}" data-post="${esc(m[3])}"` : ''}>${esc(n.value)}</p>
      <p class="stat-l">${esc(n.label)}</p>
      ${proofChip(t, anchor)}
    </div>`;
  }).join('') + '\n    ',
  ...Object.fromEntries(data.cases.map(c => [`case-proof:${c.id}`, () => {
    const t = c.proof.tier, pub = c.proof.sources.filter(id => id !== 'resume');
    return `
        <div class="cp">
          ${proofChip(t)}
          <p class="cp-what">${WHAT[t]}</p>${pub.length ? `
          <details class="srcs"><summary>${pub.length} public source${pub.length > 1 ? 's' : ''}, and what each proves</summary>
            <ol>${sourcesList(pub)}
            </ol>
          </details>` : ''}
        </div>
        `;
  }])),
  ...Object.fromEntries(data.projects.map(x => [`project-proof:${x.id}`, () => {
    const src = srcById[x.proof.sources[0]], sn = src.snapshot;
    const agent = sn.authors.filter(a => a.name !== 'Parth Aggarwal').reduce((s, a) => s + a.commits, 0);
    return `
          <div class="p-proof" data-repo="${esc(src.repo)}">
            ${proofChip('verified', src.url)}
            <span class="p-git"><b data-live="commits">${sn.commits}</b> commits · ${fmtDate(sn.first)} → ${fmtDate(sn.last)}</span>${agent ? `
            <span class="p-agent">${agent} of ${sn.commits} commits by Claude, an AI coding agent</span>` : ''}
          </div>
          `;
  }])),
  journey: () => data.roles.map(r => `
      <li class="jr" data-reveal data-r="JOURNEY|${esc(r.company)}|${esc(r.period.split(' - ')[0])}">
        <span class="jr-when">${period(r.period)}</span>
        <div class="jr-what">
          <p class="jr-role">${esc(r.title.split(' - ')[0])}${r.title.includes(' - ') ? ` <span>${esc(r.title.split(' - ').slice(1).join(' - '))}</span>` : ''}</p>
          <p class="jr-co">${esc(r.company)} · ${esc(r.location.split(',')[0])}</p>
          <p class="jr-scope">${esc(r.scope)}</p>
        </div>
        ${proofChip(r.proof.tier)}
      </li>`).join('') + '\n    ',
  principles: () => data.principles.map((x, i) => {
    const [lead, ...rest] = x.split(': ');
    return `
      <li data-reveal data-d="${i + 1}"><span class="pr-n">0${i + 1}</span><p>${rest.length ? `<b>${esc(lead)}.</b> ${esc(rest.join(': '))}` : `<b>${esc(x)}</b>`}</p></li>`;
  }).join('') + '\n    ',
  awards: () => data.awards.map(a => `
        <li><span class="li-t">${esc(a.name)}</span><span class="li-m">${esc(a.org)} · ${esc(a.date)}</span><span class="li-d">${esc(a.for)}</span></li>`).join('') + '\n      ',
  writing: () => data.writing.map(w => `
        <li><a class="li-t" href="${esc(w.url)}" target="_blank" rel="noopener">${esc(w.title)} <span aria-hidden="true">↗</span></a><span class="li-m">Medium · ${w.date ? fmtDate(w.date) : ''}</span></li>`).join('') + '\n      ',
};
const gen = html => html.replace(/(<!-- gen:([\w:-]+) -->)[\s\S]*?(<!-- \/gen -->)/g, (all, open, name, close) => {
  if (!blocks[name]) throw new Error(`index.html asks for an unknown block: ${name}`);
  return open + blocks[name]() + close;
});
const indexHtml = gen(read('index.html'));

const files = { 'server/worker.js': out, 'llms.txt': llms, 'index.html': indexHtml };
if (process.argv.includes('--check')) {
  const stale = Object.entries(files).filter(([f, text]) => { try { return readFileSync(root + f, 'utf8') !== text; } catch { return true; } }).map(([f]) => f);
  if (stale.length) { console.error(`${stale.join(', ')} stale: run node tools/build.mjs`); process.exit(1); }
  console.log('server/worker.js, llms.txt and index.html are up to date');
} else {
  for (const [f, text] of Object.entries(files)) {
    writeFileSync(root + f, text);
    console.log(`wrote ${f} (${(text.length / 1024).toFixed(1)} KB)`);
  }
}
