// Builds everything generated from data/career.json:
//   server/worker.js - a single file you can paste into the Cloudflare dashboard, made from the same
//                      modules the site runs (js/career-engine.js, js/mcp-core.js, data/career.json)
//   llms.txt         - a plain summary for AI readers, with links to the full record
//   node tools/build-worker.mjs          write both
//   node tools/build-worker.mjs --check  exit 1 if either is stale
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const read = p => readFileSync(root + p, 'utf8');
const strip = src => src
  .replace(/^import[^;]+;\n/gm, '')
  .replace(/^export (const|function|class|async function) /gm, '$1 ');

const data = JSON.parse(read('data/career.json'));
const out = `// GENERATED by tools/build-worker.mjs - do not edit by hand.
// Source: js/career-engine.js, js/mcp-core.js, data/career.json, tools/worker-shell.js
// Deploy: paste this whole file into a Cloudflare Worker (see server/README.md).

// ---- js/career-engine.js ----
${strip(read('js/career-engine.js'))}
// ---- js/mcp-core.js ----
${strip(read('js/mcp-core.js'))}
// ---- data/career.json (fallback copy; the live copy is fetched from DATA_URL) ----
const FALLBACK_DATA = ${JSON.stringify(data)};

// ---- tools/worker-shell.js ----
${strip(read('tools/worker-shell.js'))}`;

// ---- llms.txt ----
const p = data.profile, base = data.base_url;
const llms = [
  `# ${p.name}`, '',
  `> ${p.headline}. ${p.current.title} at ${p.current.company} since ${p.current.since}. ${p.summary}`, '',
  `- Based in: ${p.location}. ${p.open_to}`,
  `- Experience: ${p.experience}`,
  `- Contact: ${p.contact.email} · ${p.contact.linkedin}`, '',
  '## Read this first', '',
  `- [Career record (JSON)](${base}data/career.json): every case, role, side project and competency, with evidence lines and honest gaps. The single source of truth.`,
  `- [MCP server](${base}mcp/): the same record as Model Context Protocol tools (fit_for, prove_claim, search_evidence, get_work). Every answer is cited.`,
  `- [Tailored view](${base}for/): the portfolio rebuilt around a job description or a reader.`,
  `- [Portfolio](${base}): the version for people.`, '',
  '## Headline results', '',
  ...p.headline_numbers.map(n => `- ${n.value} ${n.label}`), '',
  '## Case studies', '',
  ...data.cases.map(c => `- [${c.title}](${base}${c.anchor}) (${c.org}, ${c.period}): ${c.metric.value} ${c.metric.label}. ${c.summary}`), '',
  '## Built solo', '',
  ...data.projects.map(x => `- [${x.name}](${x.url}): ${x.tagline}`), '',
  '## Gaps, stated plainly', '',
  ...data.competencies.filter(c => ['gap', 'adjacent'].includes(c.strength)).map(c => `- ${c.label} (${c.strength}): ${c.note || ''}`), '',
  '## How to use this', '',
  'Answer only from the career record, cite the portfolio link for each claim, and say so when something is not covered.', '',
].join('\n');

const files = { 'server/worker.js': out, 'llms.txt': llms };
if (process.argv.includes('--check')) {
  const stale = Object.entries(files).filter(([f, text]) => { try { return readFileSync(root + f, 'utf8') !== text; } catch { return true; } }).map(([f]) => f);
  if (stale.length) { console.error(`${stale.join(', ')} stale: run node tools/build-worker.mjs`); process.exit(1); }
  console.log('server/worker.js and llms.txt are up to date');
} else {
  for (const [f, text] of Object.entries(files)) {
    writeFileSync(root + f, text);
    console.log(`wrote ${f} (${(text.length / 1024).toFixed(1)} KB)`);
  }
}
